### ISSUE TITLE
getEvents is causing error

### ISSUE THREAD

**Issue by rht** [ifo/gozulipbot#2]
@ifo this is a bug reported from Matterbridge: https://github.com/42wim/matterbridge/issues/1047. The gist is that getEvents is not capturing any event from the Zulip side to be sent over to IRC / Slack side. There has been a conjecture in this [comment](https://github.com/42wim/matterbridge/issues/1047#issuecomment-620732121) that the cause might be https://github.com/zulip/zulip/commit/86a7fdddd7776cc225f888f30f040524274ac24b.

**Comment by ifo** [comment]
Hey thanks! Yeah, I recently started fixing a bot of mine that uses this and found out that `getEvents` didn't work due to me passing the wrong last event id. Turns out I'd been doing it wrong the entire time! I'd thought the last event id should be the largest ID of the events you'd seen, and assumed that was something like the message id, rather than the actual id of the event being passed back. I fixed it with https://github.com/ifo/gozulipbot/commit/684aca9fd4ba35854f460e55b9000805f2e8eb6b, and also fixed reactions, which were using an outdated api endpoint.

Updating matterbridge's go.mod to `require github.com/ifo/gozulipbot v0.0.0-20200725193743-f965bc443509` _should_ fix things.

Thanks for reporting this and let me know if that works!

**Comment by ifo** [comment]
Actually, scratch that. I found some bad bugs with `EventsChan`, `EventsCallback` and `ParseEventMessages` (essentially they'll fail as soon as they get a heartbeat message). I fixed those and tagged the first module version of this at v0.0.1.

**Comment by rht** [comment]
Great, I will test on Matterbridge soon.

**Comment by rht** [comment]
I just tested by creating a bridge (via Matterbridge) between irc.freenode.net of `#python-mypy` and chat.zulip.org of `#test-here`. The message from freenode gets relayed to Zulip, but still not the other way around. Maybe I will ask the Matterbridge author to test it instead. There are several patches to ifo/gozulipbot done by Matterbridge, and I patched the code manually.
